version: "3.9"

services:

  db:
    image: mysql:8
    container_name: smp-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smp
      MYSQL_USER: smpuser
      MYSQL_PASSWORD: smp123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    image: smp-backend:latest
    container_name: smp-backend
    depends_on:
      - db
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/smp
      SPRING_DATASOURCE_USERNAME: smpuser
      SPRING_DATASOURCE_PASSWORD: smp123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: always

  frontend:
    image: smp-frontend:latest
    container_name: smp-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
    restart: always

volumes:
  db_data: